/*
 * Copyright (C) 2013 Florian Frankenberger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.lastdigitofpi.xdata.explorer;

import com.lastdigitofpi.xdata.explorer.TypeWrapperModel.TypeWrapper;
import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.tree.TreePath;

/**
 *
 * @author Florian Frankenberger
 */
public class EditDataDialog extends javax.swing.JDialog {

    private final DataElement element;

    /**
     * Creates new form EditDataDialog
     *
     * @param parent
     * @param path
     * @param element
     */
    public EditDataDialog(java.awt.Frame parent, TreePath path, DataElement element) {
        super(parent, true);
        this.element = element;

        initComponents();

        Object value = element.getValue();

        typeSelector.setModel(new TypeWrapperModel());

        typeSelector.setRenderer(new TypeWrapperRenderer());
        if (value != null) {
            for (TypeWrapper<Object> typeWrapper : TypeWrapperModel.TYPE_WRAPPERS) {
                if (typeWrapper.getType().equals(value.getClass())) {
                    valueField.setText(typeWrapper.unWrap(value));
                    typeSelector.setSelectedItem(typeWrapper);
                    break;
                }
            }
        } else {
            TypeWrapper<Object> typeWrapper = TypeWrapperModel.TYPE_WRAPPERS[TypeWrapperModel.TYPE_WRAPPERS.length - 1];
            valueField.setText(typeWrapper.unWrap(value));
            typeSelector.setSelectedItem(typeWrapper);
        }

        pathField.setText(Utils.pathToString(path));
        validateValue();

        valueField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                validateValue();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateValue();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateValue();
            }

        });

        setLocationRelativeTo(null);
    }

    private void validateValue() {
        final Object selectedItem = typeSelector.getSelectedItem();
        if (selectedItem instanceof TypeWrapper) {
            final TypeWrapper<Object> wrapper = (TypeWrapper<Object>) selectedItem;
            final String valueRaw = valueField.getText();

            Object object = wrapper.wrap(valueRaw);
            final boolean valid = object != null || !valueField.isEnabled();
            updateButton.setEnabled(valid);
            valueField.setBackground(valid ? javax.swing.UIManager.getDefaults().getColor("TextField.background") : new Color(255, 200, 200));
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typeSelector = new javax.swing.JComboBox();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Value:");

        valueField.setText("jTextField1");

        jLabel2.setText("Type:");

        typeSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeSelectorItemStateChanged(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Path:");

        pathField.setEditable(false);
        pathField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueField)
                            .addComponent(typeSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pathField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 333, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeSelectorItemStateChanged
        TypeWrapper<Object> wrapper = (TypeWrapper<Object>) typeSelector.getSelectedItem();
        valueField.setEnabled(wrapper.enableEditor());
        validateValue();
    }//GEN-LAST:event_typeSelectorItemStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        TypeWrapper<Object> wrapper = (TypeWrapper<Object>) typeSelector.getSelectedItem();
        Object newValue = wrapper.wrap(valueField.getText());
        element.setValue(newValue);

        this.setVisible(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pathField;
    private javax.swing.JComboBox typeSelector;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField valueField;
    // End of variables declaration//GEN-END:variables
}
